server:
  port: 9099

spring:
  datasource:
    url: jdbc:mysql://10.12.51.143:3306/aichat?useSSL=false&serverTimezone=UTC
    username: root
    password: rong360.com
    driver-class-name: com.mysql.cj.jdbc.Driver

    # HikariCP 连接池配置
    hikari:
      pool-name: MyHikariPool  # 连接池名称
      minimum-idle: 5         # 最小空闲连接数
      maximum-pool-size: 20   # 最大连接数
      idle-timeout: 30000     # 空闲连接超时时间(ms)
      max-lifetime: 1800000   # 连接最大生命周期(ms)
      connection-timeout: 30000 # 连接超时时间(ms)
      connection-test-query: SELECT 1  # 连接测试查询